#!/usr/bin/env bash

# This is a two-stage detection variant. The region proposals are generated by a DefDETR variant and fed into the decoder for refinement.
# To create object proposals, we use an encoder-only DefDETR where each pixel is assigned an object query. The proposals are the top-scoring bboxes. 

set -x

EXP_DIR=exps/r50_deformable_detr_plus_iterative_bbox_refinement_plus_plus_two_stage
PY_ARGS=${@:1}

python -u main.py \
    --output_dir ${EXP_DIR} \
    --with_box_refine \
    --two_stage \
    ${PY_ARGS}
